apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     60s
      evaluation_interval: 60s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      
      - job_name: Confluent Cloud
        scrape_interval: 1m
        scrape_timeout: 1m
        honor_timestamps: true
        static_configs:
          - targets:
            - api.telemetry.confluent.cloud
        scheme: https
        basic_auth:
          username: 'API-KEY'
          password: 'API-SECRET'
        metrics_path: /v2/metrics/cloud/export
        params:
          "resource.kafka.id":
            - 'lkc-cluster1'
            - 'lkc-cluster2'
            - 'lkc-cluster3'
            "resource.ksql.id":
              - 'lksqlc-cluster1'
              - 'lksqlc-cluster2'
            "resource.schema_registry.id":
              - 'lsrc-cluster1'
              - 'lsrc-cluster2'

